name: nhost_query_stress_test
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dotenv: ^3.0.0
  graphql:
  nhost_graphql_adapter: ^1.0.0
  nhost_sdk: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
