name: nhost_query_stress_test
description: A simple command-line application.
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
